all:
  children:
    terraform-ansible:
      hosts:
        terraform-ansible:
          ansible_host: 34.222.153.228
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /mnt/c/Users/renat/OneDrive/Área de Trabalho/terraform/pan/raco14-oregon.pem
