- hosts: terraform-ansible
  tasks:
  -  name: criando arquivo
     copy:
       dest: /home/ubuntu/index.html
       content: <h1>Renato DevOps 2024</h1>
  -  name:  criando servidor
     shell: "nohup busybox httpd -f -p 8080 &"