- hosts: terraform-ansible
  tasks:
  -  name: criando arquivo
     copy:
       dest: /home/ubuntu/index.html
       content: <h1>RENATO ANALISTA CLOUD AWS SENIOR 2025</h1>
  -  name:  criando servidor
     shell: "nohup busybox httpd -f -p 8080 &"